[workspace]
resolver = "2"
members = ["sentinel_cli", "sentinel_core"]

[workspace.dependencies]
clap = { version = "4.5.47", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
