[package]
name = "sentinel_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { workspace = true, features = ["derive"] }
sentinel_core = { path = "../sentinel_core" }
tokio = { workspace = true, features = ["full"] }
toml = "0.9.6"
