[package]
name = "sentinel_core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
arrow = "56.1.0"
async-trait = "0.1.89"
heck-but-macros = "0.0.1"
inventory = "0.3.21"
petgraph = "0.8.2"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
toml = "0.9.5"
